all:
  children:
    active_hosts:
      # Hosts em produção
    active_vms:
      # VMs em produção
      hosts:
        node1guest1.tcc.local:
          ansible_host: 192.168.0.210
          mgmt_mac: "525400AA0002"
          lan_mac: "525400AA0001"
          wan_mac: "525400AA0000"
          vm_id: "1"
          vm_host_id: "1"
          mode: "master-init"
        node1guest2.tcc.local:
          ansible_host: 192.168.0.215
          mgmt_mac: "525400AA0102"
          lan_mac: "525400AA0101"
          wan_mac: "525400AA0100"
          vm_id: "2"
          vm_host_id: "1"
          mode: "worker"
        node2guest3.tcc.local:
          ansible_host: 192.168.0.220
          mgmt_mac: "525400AA0202"
          lan_mac: "525400AA0201"
          wan_mac: "525400AA0200"
          vm_id: "3"
          vm_host_id: "2"
          mode: "worker"
    active_master:
    # Deixar sempre o Master Ativo do Cluster com IP e mode = master-active. Utilizado para ingressar workers ao Cluster
      hosts:
        node1guest1.tcc.local:
          ansible_host: 192.168.0.210
          mode: "master-active"
    new_hosts:
      # Novas máquinas físicas a serem provisionadas no ambiente.
      hosts:
        node1.tcc.local:
          ansible_host: 192.168.0.200
          host_id: "1"
        node2.tcc.local:
          ansible_host: 192.168.0.201
          host_id: "2"
    new_vm_hosts:
      # Máquinas físicas em produção que receberão novas VMs.
      hosts:
        node1.tcc.local:
          ansible_host: 192.168.0.200
          host_id: "1"
        node2.tcc.local:
          ansible_host: 192.168.0.201
          host_id: "2"
    new_vms:
      # Novas VMs a serem adicionadas ao ambiente.
      hosts:
        node1guest1.tcc.local:
          ansible_host: 192.168.0.210
          mgmt_mac: "525400AA0002"
          lan_mac: "525400AA0001"
          wan_mac: "525400AA0000"
          vm_id: "1"
          vm_host_id: "1"
          mode: "master-init"
        node1guest2.tcc.local:
          ansible_host: 192.168.0.215
          mgmt_mac: "525400AA0102"
          lan_mac: "525400AA0101"
          wan_mac: "525400AA0100"
          vm_id: "2"
          vm_host_id: "1"
          mode: "worker"
        node2guest3.tcc.local:
          ansible_host: 192.168.0.220
          mgmt_mac: "525400AA0202"
          lan_mac: "525400AA0201"
          wan_mac: "525400AA0200"
          vm_id: "3"
          vm_host_id: "2"
          mode: "worker"
    teste-tmp:
      # Grupo para testes.