---
- name: Deploying Service
  hosts: teste-tmp
  become: yes

  handlers:
    - include: "handlers/main.yml"
  
  roles:
    - kubernetes/deploy_service

  vars_files:
    - /etc/ansible/vars/main.yml