---
- name: Deploy de máquina física
  hosts:  new_hosts
  strategy: free

  roles:
    - name # ok
    - post-install # ok
    - repos # ok
    - utils # ok
    - kvm # ok
    - ansible # ok
    - vagrant # ok

  vars_files:
    - ../../vars/main.yml