---
- name: Deploy de ambiente teste para ipsec ipv6 com container
  hosts:  teste-tmp

  roles:
    - name # ok
    - post-install # ok
    - network # vamos pensar depois - por enquanto está manual
    - repos # ok
    - utils # ok
    - docker # ok
    - ipsec-prereqs # ok

  vars_files:
    - /etc/ansible/vars/main.yml